/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as DoveSiamoRouteImport } from './routes/dove-siamo'
import { Route as IlGiardinoRouteImport } from './routes/il-giardino'
import { Route as LaMansardaRouteImport } from './routes/la-mansarda'
import { Route as LaStrutturaRouteImport } from './routes/la-struttura'
import { Route as RoomsIndexRouteImport } from './routes/rooms.index'
import { Route as RoomsSlugRouteImport } from './routes/rooms.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const DoveSiamoRoute = DoveSiamoRouteImport.update({
  id: '/dove-siamo',
  path: '/dove-siamo',
  getParentRoute: () => rootRouteImport,
} as any)
const IlGiardinoRoute = IlGiardinoRouteImport.update({
  id: '/il-giardino',
  path: '/il-giardino',
  getParentRoute: () => rootRouteImport,
} as any)
const LaMansardaRoute = LaMansardaRouteImport.update({
  id: '/la-mansarda',
  path: '/la-mansarda',
  getParentRoute: () => rootRouteImport,
} as any)
const LaStrutturaRoute = LaStrutturaRouteImport.update({
  id: '/la-struttura',
  path: '/la-struttura',
  getParentRoute: () => rootRouteImport,
} as any)
const RoomsIndexRoute = RoomsIndexRouteImport.update({
  id: '/rooms/',
  path: '/rooms/',
  getParentRoute: () => rootRouteImport,
} as any)
const RoomsSlugRoute = RoomsSlugRouteImport.update({
  id: '/rooms/$slug',
  path: '/rooms/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/dove-siamo': typeof DoveSiamoRoute
  '/il-giardino': typeof IlGiardinoRoute
  '/la-mansarda': typeof LaMansardaRoute
  '/la-struttura': typeof LaStrutturaRoute
  '/rooms/$slug': typeof RoomsSlugRoute
  '/rooms/': typeof RoomsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/dove-siamo': typeof DoveSiamoRoute
  '/il-giardino': typeof IlGiardinoRoute
  '/la-mansarda': typeof LaMansardaRoute
  '/la-struttura': typeof LaStrutturaRoute
  '/rooms/$slug': typeof RoomsSlugRoute
  '/rooms': typeof RoomsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/dove-siamo': typeof DoveSiamoRoute
  '/il-giardino': typeof IlGiardinoRoute
  '/la-mansarda': typeof LaMansardaRoute
  '/la-struttura': typeof LaStrutturaRoute
  '/rooms/$slug': typeof RoomsSlugRoute
  '/rooms/': typeof RoomsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/dove-siamo'
    | '/il-giardino'
    | '/la-mansarda'
    | '/la-struttura'
    | '/rooms/$slug'
    | '/rooms/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/dove-siamo'
    | '/il-giardino'
    | '/la-mansarda'
    | '/la-struttura'
    | '/rooms/$slug'
    | '/rooms'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/dove-siamo'
    | '/il-giardino'
    | '/la-mansarda'
    | '/la-struttura'
    | '/rooms/$slug'
    | '/rooms/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  DoveSiamoRoute: typeof DoveSiamoRoute
  IlGiardinoRoute: typeof IlGiardinoRoute
  LaMansardaRoute: typeof LaMansardaRoute
  LaStrutturaRoute: typeof LaStrutturaRoute
  RoomsSlugRoute: typeof RoomsSlugRoute
  RoomsIndexRoute: typeof RoomsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dove-siamo': {
      id: '/dove-siamo'
      path: '/dove-siamo'
      fullPath: '/dove-siamo'
      preLoaderRoute: typeof DoveSiamoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/il-giardino': {
      id: '/il-giardino'
      path: '/il-giardino'
      fullPath: '/il-giardino'
      preLoaderRoute: typeof IlGiardinoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/la-mansarda': {
      id: '/la-mansarda'
      path: '/la-mansarda'
      fullPath: '/la-mansarda'
      preLoaderRoute: typeof LaMansardaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/la-struttura': {
      id: '/la-struttura'
      path: '/la-struttura'
      fullPath: '/la-struttura'
      preLoaderRoute: typeof LaStrutturaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rooms/': {
      id: '/rooms/'
      path: '/rooms'
      fullPath: '/rooms/'
      preLoaderRoute: typeof RoomsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rooms/$slug': {
      id: '/rooms/$slug'
      path: '/rooms/$slug'
      fullPath: '/rooms/$slug'
      preLoaderRoute: typeof RoomsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  DoveSiamoRoute: DoveSiamoRoute,
  IlGiardinoRoute: IlGiardinoRoute,
  LaMansardaRoute: LaMansardaRoute,
  LaStrutturaRoute: LaStrutturaRoute,
  RoomsSlugRoute: RoomsSlugRoute,
  RoomsIndexRoute: RoomsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
